#端口
server:
  port: 8080
#spring的配置
spring:
  #数据源的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 腾讯云 mysql 数据库连接
    url: jdbc:mysql://cdb-csnz8qhs.cd.tencentcdb.com:10087/code-fusheng-his?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: code-fusheng
    #注入数据源的类型   默认的为HikariDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      min-idle: 5
      validation-query: select x
      initial-size: 3
      max-wait: 5000
      stat-view-servlet:
        #        login-username: root
        #        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
        enabled: true  #启用数据源监控
  #配置redis
  redis:
    port: 6390
    host: www.fusheng.xyz   # 175.24.45.179
    password: 123456
  # 前台日期格式化
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  # 后台日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#shiro配置
shiro:
  anon-urls:
    - /login/doLogin*
    - /login/captcha*
    - /login/logout*
    - /druid/**
  authc-urls:
    - /**
#mybatisplus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
#fastdfs的配置
fdfs:
  so-timeout: 2500       # 读取时间
  connect-timeout: 600   # 连接超时时间
  thumb-image:           # 缩略图
    width: 100
    height: 100
  tracker-list:          # tracker服务配置地址列表
    - ww.fusheng.xyz:22122    # 175.24.45.179:22122
upload:
  base-url: http://fusheng.xyz    # http://175.24.45.179/
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
    - image/gif
    - audio/mpeg
#dubbo配置
dubbo:
  application:
    name: his-system-web-service
  registry:
    address: zookeeper://www.fusheng.xyz:2184
  consumer:
    check: false
